"use client";

import {
  Anchor,
  Archive,
  Baby,
  Bike,
  Bird,
  BookOpen,
  Bone,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  CarFront,
  CircleDot,
  Clock3,
  Cloud,
  Cog,
  Compass,
  Cpu,
  Crown,
  Factory,
  Fish,
  Flag,
  Flame,
  Footprints,
  Gamepad2,
  Gem,
  GraduationCap,
  Grid2x2,
  Hammer,
  Headphones,
  Heart,
  HeartHandshake,
  Home,
  Hotel,
  KeyRound,
  Landmark,
  LandPlot,
  Languages,
  Laptop,
  Megaphone,
  Monitor,
  Music,
  Paintbrush,
  Palmtree,
  Plane,
  Accessibility,
  Tent,
  PawPrint,
  Plug,
  Printer,
  Recycle,
  RefreshCw,
  Sailboat,
  Scale,
  Scissors,
  Search,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Tablet,
  Ticket,
  Tractor,
  Trees,
  Truck,
  Tv,
  UserSearch,
  Users,
  Utensils,
  Warehouse,
  Watch,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  laptop: Laptop,
  sofa: Sofa,
  shirt: Shirt,
  car: Car,
  suv: CarFront,
  van: Bus,
  building: Building2,
  buildings: Building2,
  home: Home,
  hotel: Hotel,
  store: Store,
  land: LandPlot,
  palmtree: Palmtree,
  tent: Tent,
  plane: Plane,
  access: Accessibility,
  cpu: Cpu,
  bike: Bike,
  gamepad: Gamepad2,
  truck: Truck,
  paw: PawPrint,
  grid: Grid2x2,
  headphones: Headphones,
  monitor: Monitor,
  tablet: Tablet,
  key: KeyRound,
  wrench: Wrench,
  zap: Zap,
  clock: Clock3,
  calendar: Clock3,
  refresh: RefreshCw,
  shield: Shield,
  stethoscope: Stethoscope,
  "user-search": UserSearch,
  sparkles: Sparkles,
  megaphone: Megaphone,
  star: Star,
  flame: Flame,
  ship: Ship,
  sail: Sailboat,
  anchor: Anchor,
  compass: Compass,
  wind: Wind,
  cog: Cog,
  bag: ShoppingBag,
  camera: Camera,
  cake: Cake,
  printer: Printer,
  recycle: Recycle,
  search: Search,
  flag: Flag,
  tv: Tv,
  plug: Plug,
  watch: Watch,
  baby: Baby,
  book: BookOpen,
  music: Music,
  gem: Gem,
  archive: Archive,
  landmark: Landmark,
  trees: Trees,
  tractor: Tractor,
  factory: Factory,
  hammer: Hammer,
  paint: Paintbrush,
  graduation: GraduationCap,
  languages: Languages,
  scale: Scale,
  ticket: Ticket,
  users: Users,
  bone: Bone,
  fish: Fish,
  bird: Bird,
  "heart-handshake": HeartHandshake,
  heart: Heart,
  briefcase: Briefcase,
  utensils: Utensils,
  circle: CircleDot,
  warehouse: Warehouse,
  crown: Crown,
  scissors: Scissors,
  footprints: Footprints,
  cloud: Cloud,
};

const TONES = ["is-mint", "is-sky", "is-violet", "is-amber", "is-rose", "is-teal", "is-slate", "is-lime"] as const;

const TONE_BY_ICON: Record<string, (typeof TONES)[number]> = {
  building: "is-sky",
  buildings: "is-sky",
  home: "is-sky",
  hotel: "is-sky",
  store: "is-teal",
  land: "is-lime",
  palmtree: "is-teal",
  tent: "is-amber",
  plane: "is-sky",
  access: "is-teal",
  car: "is-violet",
  suv: "is-violet",
  van: "is-slate",
  truck: "is-amber",
  ship: "is-sky",
  sail: "is-sky",
  anchor: "is-sky",
  compass: "is-teal",
  wind: "is-sky",
  cog: "is-slate",
  wrench: "is-amber",
  circle: "is-slate",
  bag: "is-rose",
  shirt: "is-rose",
  sofa: "is-amber",
  smartphone: "is-violet",
  laptop: "is-sky",
  tablet: "is-sky",
  monitor: "is-slate",
  cpu: "is-violet",
  camera: "is-slate",
  tv: "is-slate",
  plug: "is-amber",
  watch: "is-violet",
  gem: "is-rose",
  baby: "is-rose",
  sparkles: "is-amber",
  gamepad: "is-violet",
  book: "is-sky",
  music: "is-rose",
  bike: "is-teal",
  trees: "is-lime",
  tractor: "is-lime",
  factory: "is-slate",
  hammer: "is-amber",
  paint: "is-violet",
  graduation: "is-sky",
  languages: "is-teal",
  scale: "is-slate",
  ticket: "is-rose",
  users: "is-teal",
  paw: "is-amber",
  bone: "is-amber",
  fish: "is-sky",
  bird: "is-teal",
  utensils: "is-rose",
  "heart-handshake": "is-rose",
  heart: "is-rose",
  scissors: "is-rose",
  zap: "is-amber",
  clock: "is-violet",
  megaphone: "is-rose",
  star: "is-amber",
  flame: "is-rose",
  key: "is-teal",
  refresh: "is-mint",
  shield: "is-sky",
  warehouse: "is-slate",
  crown: "is-amber",
};

export function iconTone(name: string) {
  if (TONE_BY_ICON[name]) return TONE_BY_ICON[name];
  let n = 0;
  for (let i = 0; i < name.length; i++) n += name.charCodeAt(i);
  return TONES[n % TONES.length];
}

export function CategoryIcon({
  name,
  className = "h-5 w-5",
}: {
  name: string;
  className?: string;
}) {
  const Icon = MAP[name] ?? Grid2x2;
  return <Icon className={className} strokeWidth={1.7} />;
}
