/**
 * Permanently removes demo listings (and rows that cascade from them). Demo seller accounts are kept.
 *
 * A listing is a target only if ALL of these hold:
 *   - listing_no starts with "APD-"
 *   - id is one of the seed listing ids (prisma/seed-demo.ts stableUuid)
 *   - seller_id is one of the 8 seed demo seller ids, and that user's email ends with @demo.alsatport.com
 *
 * Dry-run (default, read-only):
 *   npx tsx scripts/purge-demo-listings.ts
 * Execute (single transaction, rolls back on any failed check):
 *   npx tsx scripts/purge-demo-listings.ts --execute --expect=<target count from dry-run>
 *
 * DATABASE_URL must be set in the environment; it is never printed.
 *
 * Without DB access, write the same purge as one atomic SQL statement (for the Neon SQL Editor):
 *   npx tsx scripts/purge-demo-listings.ts --sql=<out.sql> --expect=<count>
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { Prisma, PrismaClient } from "@prisma/client";
import { DEMO_LISTING_PREFIX, DEMO_SELLERS, buildDemoListings } from "../src/data/demoSeed";

const DEMO_EMAIL_SUFFIX = "@demo.alsatport.com";
const args = process.argv.slice(2);
const EXECUTE = args.includes("--execute");
const expectArg = args.find((a) => a.startsWith("--expect="));
const EXPECT = expectArg ? Number(expectArg.slice("--expect=".length)) : NaN;

function redact(text: string) {
  return text.replace(/postgres(?:ql)?:\/\/\S+/gi, "[redacted-db-url]");
}

function stableUuid(key: string) {
  const h = createHash("sha1").update(`alsatport.demo:${key}`).digest();
  const b = Buffer.from(h.subarray(0, 16));
  b[6] = (b[6]! & 0x0f) | 0x50;
  b[8] = (b[8]! & 0x3f) | 0x80;
  const hex = b.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

class Abort extends Error {}

const sqlArg = args.find((a) => a.startsWith("--sql="));
if (sqlArg) {
  if (!(Number.isInteger(EXPECT) && EXPECT > 0)) {
    console.error("--sql requires --expect=<count>.");
    process.exit(2);
  }
  const out = sqlArg.slice("--sql=".length);
  writeFileSync(out, purgeSql(EXPECT), "utf8");
  console.log(`wrote ${out} (expected targets ${EXPECT}, seed ids ${new Set(buildDemoListings().map((l) => l.id)).size})`);
  process.exit(0);
}

function purgeSql(expected: number) {
  const seed = [...new Set(buildDemoListings().map((l) => stableUuid(l.id)))];
  const sellers = [...new Set(DEMO_SELLERS.map((s) => stableUuid(`seller:${s.id}`)))];
  const arr = (ids: string[]) => `ARRAY[\n    ${ids.map((id) => `'${id}'`).join(",\n    ")}\n  ]::uuid[]`;
  return `-- AlsatPort: permanent purge of demo listings (demo seller accounts are kept).
-- Generated by scripts/purge-demo-listings.ts. One DO statement = one atomic transaction:
-- any RAISE EXCEPTION below rolls back everything.
-- Target = listing_no LIKE '${DEMO_LISTING_PREFIX}%' AND id in seed ids AND seller is a seed demo seller with a ${DEMO_EMAIL_SUFFIX} email.

-- Read-only preview: reports attached to ${DEMO_LISTING_PREFIX} listings, before anything changes.
SELECT
  count(*) FILTER (WHERE r.target_type = 'listing') AS listing_reports_on_apd,
  count(*) FILTER (WHERE r.target_type = 'listing' AND u.email NOT ILIKE '%${DEMO_EMAIL_SUFFIX}') AS by_non_demo_reporters,
  count(*) FILTER (WHERE r.target_type <> 'listing') AS other_reports_linked_kept
FROM reports r
JOIN listings l ON l.id = r.listing_id
JOIN users u ON u.id = r.reporter_id
WHERE l.listing_no LIKE '${DEMO_LISTING_PREFIX}%';

DO $purge$
DECLARE
  expected     int := ${expected};
  seed_ids     uuid[] := ${arr(seed)};
  seller_ids   uuid[] := ${arr(sellers)};
  demo_sellers uuid[];
  target       uuid[];
  real_ids     uuid[];
  n            int;
  deleted      int;
  listing_reports      int;
  listing_reports_real int;
  reports_total        int;
  reports_on_real      int;
  reports_gone         int;
BEGIN
  -- Only these delete rules are acceptable; anything else (e.g. a CASCADE into conversations) aborts.
  SELECT count(*) INTO n
  FROM pg_constraint c JOIN pg_class ch ON ch.oid = c.conrelid
  WHERE c.contype = 'f' AND c.confrelid = 'public.listings'::regclass
    AND NOT (
      (ch.relname IN ('listing_images', 'favorites', 'qr_tokens', 'listing_promotions') AND c.confdeltype = 'c')
      OR (ch.relname IN ('conversations', 'payments', 'reports', 'notifications', 'seller_reviews') AND c.confdeltype = 'n')
    );
  IF n > 0 THEN RAISE EXCEPTION 'ABORTED: % unexpected foreign key rule(s) on listings', n; END IF;

  SELECT array_agg(id) INTO demo_sellers
  FROM users WHERE id = ANY (seller_ids) AND lower(email) LIKE '%${DEMO_EMAIL_SUFFIX}';
  IF coalesce(cardinality(demo_sellers), 0) <> ${sellers.length} THEN
    RAISE EXCEPTION 'ABORTED: demo sellers verified %/${sellers.length}', coalesce(cardinality(demo_sellers), 0);
  END IF;

  SELECT count(*) INTO n FROM listings WHERE listing_no LIKE '${DEMO_LISTING_PREFIX}%' AND NOT (seller_id = ANY (demo_sellers));
  IF n > 0 THEN RAISE EXCEPTION 'ABORTED: % ${DEMO_LISTING_PREFIX} listing(s) belong to non-demo users', n; END IF;
  SELECT count(*) INTO n FROM listings WHERE listing_no LIKE '${DEMO_LISTING_PREFIX}%' AND NOT (id = ANY (seed_ids));
  IF n > 0 THEN RAISE EXCEPTION 'ABORTED: % ${DEMO_LISTING_PREFIX} listing(s) are not seed listings', n; END IF;

  SELECT array_agg(id) INTO target FROM listings
  WHERE listing_no LIKE '${DEMO_LISTING_PREFIX}%' AND id = ANY (seed_ids) AND seller_id = ANY (demo_sellers);
  IF coalesce(cardinality(target), 0) <> expected THEN
    RAISE EXCEPTION 'ABORTED: target count % <> expected %; nothing deleted', coalesce(cardinality(target), 0), expected;
  END IF;

  SELECT count(*) INTO n FROM listing_promotions WHERE listing_id = ANY (target) AND NOT (user_id = ANY (demo_sellers));
  IF n > 0 THEN RAISE EXCEPTION 'ABORTED: % promotion(s) on demo listings bought by non-demo users', n; END IF;

  -- reports_target_shape requires listing_id for target_type 'listing', so SET NULL cannot apply to those rows.
  -- Any other CHECK on listing_id in the SET NULL tables is unknown here: abort instead of guessing.
  SELECT count(*) INTO n
  FROM pg_constraint c JOIN pg_class ch ON ch.oid = c.conrelid
  WHERE c.contype = 'c'
    AND ch.relname IN ('conversations', 'payments', 'reports', 'notifications', 'seller_reviews')
    AND pg_get_constraintdef(c.oid) ILIKE '%listing_id%'
    AND c.conname <> 'reports_target_shape';
  IF n > 0 THEN RAISE EXCEPTION 'ABORTED: % unexpected CHECK constraint(s) on listing_id', n; END IF;

  SELECT coalesce(array_agg(id), '{}') INTO real_ids FROM listings WHERE NOT (id = ANY (target));

  SELECT count(*) INTO listing_reports FROM reports WHERE target_type = 'listing' AND listing_id = ANY (target);
  SELECT count(*) INTO listing_reports_real FROM reports
  WHERE target_type = 'listing' AND listing_id = ANY (target) AND NOT (reporter_id = ANY (demo_sellers));
  SELECT count(*) INTO reports_total FROM reports;
  SELECT count(*) INTO reports_on_real FROM reports WHERE listing_id = ANY (real_ids);
  RAISE NOTICE 'listing reports on demo listings: % (filed by non-demo users: %)', listing_reports, listing_reports_real;

  DELETE FROM listing_images WHERE listing_id = ANY (target);
  DELETE FROM favorites WHERE listing_id = ANY (target);
  DELETE FROM qr_tokens WHERE listing_id = ANY (target);
  DELETE FROM listing_promotions WHERE listing_id = ANY (target);
  -- Only reports whose subject is a demo listing; user/message reports keep their row (listing link -> NULL).
  DELETE FROM reports WHERE target_type = 'listing' AND listing_id = ANY (target);
  GET DIAGNOSTICS reports_gone = ROW_COUNT;
  IF reports_gone <> listing_reports THEN
    RAISE EXCEPTION 'ROLLED BACK: deleted % report(s) <> counted %', reports_gone, listing_reports;
  END IF;
  DELETE FROM listings
  WHERE id = ANY (target) AND listing_no LIKE '${DEMO_LISTING_PREFIX}%' AND seller_id = ANY (demo_sellers);
  GET DIAGNOSTICS deleted = ROW_COUNT;
  IF deleted <> expected THEN RAISE EXCEPTION 'ROLLED BACK: deleted % <> expected %', deleted, expected; END IF;

  SELECT count(*) INTO n FROM listings WHERE id = ANY (real_ids);
  IF n <> cardinality(real_ids) THEN RAISE EXCEPTION 'ROLLED BACK: real listings % -> %', cardinality(real_ids), n; END IF;
  SELECT count(*) INTO n FROM listings WHERE listing_no LIKE '${DEMO_LISTING_PREFIX}%';
  IF n <> 0 THEN RAISE EXCEPTION 'ROLLED BACK: % ${DEMO_LISTING_PREFIX} listing(s) left', n; END IF;
  SELECT count(*) INTO n FROM users WHERE id = ANY (demo_sellers);
  IF n <> ${sellers.length} THEN RAISE EXCEPTION 'ROLLED BACK: demo accounts % <> ${sellers.length}', n; END IF;
  SELECT count(*) INTO n FROM reports WHERE listing_id = ANY (real_ids);
  IF n <> reports_on_real THEN RAISE EXCEPTION 'ROLLED BACK: reports on real listings % -> %', reports_on_real, n; END IF;
  SELECT count(*) INTO n FROM reports;
  IF n <> reports_total - listing_reports THEN
    RAISE EXCEPTION 'ROLLED BACK: reports % -> % (expected %)', reports_total, n, reports_total - listing_reports;
  END IF;

  RAISE NOTICE 'COMMITTED: deleted % demo listings and % demo-listing report(s), kept % real listing(s)', deleted, listing_reports, cardinality(real_ids);
END
$purge$;

-- Read-only verification (run after the block above):
SELECT
  (SELECT count(*) FROM listings WHERE listing_no LIKE '${DEMO_LISTING_PREFIX}%') AS apd_listings_left,
  (SELECT count(*) FROM listings) AS listings_total,
  (SELECT count(*) FROM users WHERE lower(email) LIKE '%${DEMO_EMAIL_SUFFIX}') AS demo_accounts_kept;
`;
}

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is not set.");
  process.exit(2);
}
if (EXECUTE && !(Number.isInteger(EXPECT) && EXPECT > 0)) {
  console.error("--execute requires --expect=<target count shown by the dry-run>.");
  process.exit(2);
}

const prisma = new PrismaClient({ log: [] });
const seedListingIds = [...new Set(buildDemoListings().map((l) => stableUuid(l.id)))];
const seedSellerIds = [...new Set(DEMO_SELLERS.map((s) => stableUuid(`seller:${s.id}`)))];

type Db = Prisma.TransactionClient | PrismaClient;

async function demoSellerIds(db: Db) {
  const users = await db.user.findMany({ where: { id: { in: seedSellerIds } }, select: { id: true, email: true } });
  const ok = users.filter((u) => (u.email ?? "").toLowerCase().endsWith(DEMO_EMAIL_SUFFIX)).map((u) => u.id);
  return { ok, mismatched: users.length - ok.length };
}

function targetWhere(sellerIds: string[]): Prisma.ListingWhereInput {
  return {
    listingNo: { startsWith: DEMO_LISTING_PREFIX },
    id: { in: seedListingIds },
    sellerId: { in: sellerIds },
  };
}

async function survey(db: Db) {
  const sellers = await demoSellerIds(db);
  const where = targetWhere(sellers.ok);
  const targets = await db.listing.findMany({ where, select: { id: true, categoryId: true } });
  const ids = targets.map((t) => t.id);
  const inTargets = { listingId: { in: ids } };
  const notDemoUser = { notIn: sellers.ok };

  const [total, apdAll, apdNotTarget, seedIdNotTarget, demoSellerNotTarget] = await Promise.all([
    db.listing.count(),
    db.listing.count({ where: { listingNo: { startsWith: DEMO_LISTING_PREFIX } } }),
    db.listing.count({ where: { listingNo: { startsWith: DEMO_LISTING_PREFIX }, NOT: where } }),
    db.listing.count({ where: { id: { in: seedListingIds }, NOT: where } }),
    db.listing.count({ where: { sellerId: { in: sellers.ok }, NOT: where } }),
  ]);
  const related = {
    images: await db.listingImage.count({ where: inTargets }),
    imagesNotSeed: await db.listingImage.count({ where: { ...inTargets, NOT: { storageKey: { startsWith: "demo/" } } } }),
    favorites: await db.favorite.count({ where: inTargets }),
    favoritesByRealUsers: await db.favorite.count({ where: { ...inTargets, userId: notDemoUser } }),
    qrTokens: await db.qrToken.count({ where: inTargets }),
    promotions: await db.listingPromotion.count({ where: inTargets }),
    promotionsByRealUsers: await db.listingPromotion.count({ where: { ...inTargets, userId: notDemoUser } }),
    notificationsKept: await db.notification.count({ where: inTargets }),
    reviewsKept: await db.sellerReview.count({ where: inTargets }),
    conversationsKept: await db.conversation.count({ where: inTargets }),
    paymentsKept: await db.payment.count({ where: inTargets }),
    reportsKept: await db.report.count({ where: inTargets }),
  };
  const byRoot = new Map<string, number>();
  for (const t of targets) {
    const root = t.categoryId.split("-")[0]!;
    byRoot.set(root, (byRoot.get(root) ?? 0) + 1);
  }
  return { sellers, where, ids, total, apdAll, apdNotTarget, seedIdNotTarget, demoSellerNotTarget, related, byRoot };
}

function blockers(s: Awaited<ReturnType<typeof survey>>) {
  const out: string[] = [];
  if (s.sellers.ok.length !== seedSellerIds.length) out.push(`demo sellers found ${s.sellers.ok.length}/${seedSellerIds.length}`);
  if (s.sellers.mismatched > 0) out.push(`${s.sellers.mismatched} seed seller id(s) without a ${DEMO_EMAIL_SUFFIX} email`);
  if (s.apdNotTarget > 0) out.push(`${s.apdNotTarget} APD- listing(s) do not match all demo criteria (APD- count could not reach 0)`);
  if (s.related.promotionsByRealUsers > 0) out.push(`${s.related.promotionsByRealUsers} promotion(s) on demo listings were bought by non-demo users`);
  if (s.ids.length === 0) out.push("no target listings");
  return out;
}

function report(s: Awaited<ReturnType<typeof survey>>) {
  console.log(`listings total:                 ${s.total}`);
  console.log(`TARGET (all 3 criteria):        ${s.ids.length}`);
  console.log(`non-target listings (kept):     ${s.total - s.ids.length}`);
  console.log(`APD- total:                     ${s.apdAll}`);
  console.log(`APD- not matching all criteria: ${s.apdNotTarget}`);
  console.log(`seed id not matching all:       ${s.seedIdNotTarget}`);
  console.log(`demo seller, not matching all:  ${s.demoSellerNotTarget}`);
  console.log(`demo sellers verified:          ${s.sellers.ok.length}/${seedSellerIds.length} (accounts are NOT deleted)`);
  console.log("targets by root category:");
  for (const [k, v] of [...s.byRoot].sort((a, b) => b[1] - a[1])) console.log(`  ${k}: ${v}`);
  console.log("related rows removed with the listings (FK cascade):");
  console.log(`  listing_images ${s.related.images} (non-seed storage keys: ${s.related.imagesNotSeed})`);
  console.log(`  favorites ${s.related.favorites} (of which by real users: ${s.related.favoritesByRealUsers})`);
  console.log(`  qr_tokens ${s.related.qrTokens}, listing_promotions ${s.related.promotions}`);
  console.log("related rows kept, listing link set to NULL:");
  console.log(
    `  notifications ${s.related.notificationsKept}, seller_reviews ${s.related.reviewsKept}, conversations ${s.related.conversationsKept}, payments ${s.related.paymentsKept}, reports ${s.related.reportsKept}`,
  );
}

async function main() {
  const before = await survey(prisma);
  console.log(EXECUTE ? "== EXECUTE ==" : "== DRY-RUN (nothing is changed) ==");
  report(before);
  const blocked = blockers(before);
  if (blocked.length) throw new Abort(`stopped before any change: ${blocked.join("; ")}`);
  if (!EXECUTE) {
    console.log(`\nDry-run OK. To delete, run with: --execute --expect=${before.ids.length}`);
    return;
  }
  if (before.ids.length !== EXPECT) throw new Abort(`target count ${before.ids.length} != --expect=${EXPECT}; nothing deleted`);

  const result = await prisma.$transaction(
    async (tx) => {
      const s = await survey(tx);
      const again = blockers(s);
      if (again.length) throw new Abort(`stopped inside transaction: ${again.join("; ")}`);
      if (s.ids.length !== EXPECT) throw new Abort(`target count changed to ${s.ids.length}; rolled back`);

      const realIds = (await tx.listing.findMany({ where: { NOT: s.where }, select: { id: true } })).map((r) => r.id);
      await tx.report.deleteMany({ where: { targetType: "listing", listingId: { in: s.ids } } });
      const deleted = await tx.listing.deleteMany({ where: { ...s.where, id: { in: s.ids } } });
      if (deleted.count !== EXPECT) throw new Abort(`deleted ${deleted.count} != expected ${EXPECT}; rolled back`);

      const realAfter = realIds.length ? await tx.listing.count({ where: { id: { in: realIds } } }) : 0;
      if (realAfter !== realIds.length) throw new Abort(`real listings ${realIds.length} -> ${realAfter}; rolled back`);
      const apdLeft = await tx.listing.count({ where: { listingNo: { startsWith: DEMO_LISTING_PREFIX } } });
      if (apdLeft !== 0) throw new Abort(`APD- listings left: ${apdLeft}; rolled back`);
      const accountsLeft = await tx.user.count({ where: { id: { in: s.sellers.ok } } });
      return { deleted: deleted.count, real: realIds.length, apdLeft, accountsLeft };
    },
    { maxWait: 20_000, timeout: 180_000 },
  );

  const after = await prisma.listing.count({ where: { listingNo: { startsWith: DEMO_LISTING_PREFIX } } });
  console.log("\n== COMMITTED ==");
  console.log(`deleted demo listings: ${result.deleted}`);
  console.log(`real listings kept:    ${result.real} (all present)`);
  console.log(`APD- count now:        ${after}`);
  console.log(`demo accounts kept:    ${result.accountsLeft}`);
  if (after !== 0) throw new Error(`APD- count after commit is ${after}`);
}

main()
  .catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`\n${err instanceof Abort ? "ABORTED" : "ERROR"}: ${redact(msg)}`);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
